site_name: FastAPIBase
site_description: Boilerplate FastAPI moderno, seguro e escalável
site_url: https://github.com/KlebersonCollab/FastAPIBase
repo_url: https://github.com/KlebersonCollab/FastAPIBase
repo_name: KlebersonCollab/FastAPIBase
nav:
  - Início: index.md
  - Uso: usage.md
  - Autenticação & RBAC: auth.md
  - CLI: cli.md
  - API Reference: api.md
  - Segurança: security.md
  - Contribuindo: contributing.md
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true 